urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
        url(r'^$', views.index, name = 'index'),
        url(r'^create$', views.create, name = 'create'),
        url(r'^view/(?P<character_id>[0-9]+)$', views.view, name = 'view')
]

models.py
from django.db import models


RACES = [
        ('light', 'Peuple de la Lumière'),
        ('shadow', "Peuple de l'Ombre"),
        ('water', "Peuple de l'Eau"),
        ('fire', 'Peuple du Feu'),
        ('earth', 'Peuple de la Terre'),
        ('air', "Peuple de l'Air")
]


class Character(models.Model):
    name   = models.CharField(max_length = 32)
    player = models.CharField(max_length = 32)
    race   = models.CharField(max_length = 32, choices = RACES)
    level  = models.IntegerField()

    str = models.IntegerField()
    dex = models.IntegerField()
    agi = models.IntegerField()
    vig = models.IntegerField()
    vit = models.IntegerField()
    int = models.IntegerField()
    per = models.IntegerField()
    cha = models.IntegerField()
    wil = models.IntegerField()
    mem = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('view', args=[self.pk])

forms.py
from django import forms

from .models import Character


class CharacterForm(forms.ModelForm):
    class Meta:
        model = Character
        fields = '__all__'

views.py
from django.shortcuts import render, redirect, get_object_or_404

from .models import Character
from .forms import CharacterForm


def index(request):
    characters = Character.objects.all()
    return render(request, 'zgame_charactersheets/index.html',
            {'characters': characters})

def create(request):
    if request.method == 'POST':
        form = CharacterForm(request.POST)
        if form.is_valid():
            redirect(form.save())
    else:
        form = CharacterForm()

    return render(request, 'zgame_charactersheets/create.html',
            {'form': form})

def view(request, character_id):
    character = get_object_or_404(Character, pk=character_id)

    return render(request, 'zgame_charactersheets/view.html',
            {'character': character})

templates/zgame_charactersheets/create.html
{% extends "base.html" %}
{% load static %}

{% block title %}New character - Zgame characters{% endblock %}

{% block import %}
{% endblock %}

{% block content %}
    <form action={% url "create" %} method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create this character">
    </form>
{% endblock %}

templates/zgame_charactersheets/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Zgame characters{% endblock %}

{% block imports %}
<link rel="stylesheet" href={% static "zgame_charactersheets/style.css" %}>
{% endblock %}

{% block content %}
<div class="col-md-3">
    <table class="table table-hover">
        <thead>
            <th>Personnage</th>
            <th>Joueur</th>
        </thead>
        <tbody>
            {% for character in characters %}
            <tr>
                <td><a href="{{ character.get_absolute_url }}" class="cell-link">{{ character.name }}</a></td>
                <td><a href="{{ character.get_absolute_url }}" class="cell-link">{{ character.player }}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <hr>

    <p><a href="{% url "create" %}" class="btn btn-default">Create a new character</a></p>
</div>
{% endblock %}

templates/zgame_charactersheets/view.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ character.name }} - Zgame characters{% endblock %}

{% block import %}
{% endblock %}

{% block content %}
<div id="character-bio" class="row">
    <div class="col-md-4">
        <div class="panel panel-default panel-body">
            <p><b>{{ character.name }}</b> ({{ character.player }})</p>
            <p>{{ character.get_race_display }}</p>
            <p><i>Niveau {{ character.level }}</i></p>
        </div>
    </div>
</div>
<div id="character-stats" class="row">
    <div id="character-stats-physical" class="col-md-2">
        <table class="table table-condensed table-striped table-bordered">
            <tr>
                <td><b>Force</b></td>
                <td style="width:15%">{{ character.str }}</td>
            </tr>
            <tr>
                <td><b>Dextérité</b></td>
                <td style="width:15%">{{ character.dex }}</td>
            </tr>
            <tr>
                <td><b>Agilité</b></td>
                <td style="width:15%">{{ character.agi }}</td>
            </tr>
            <tr>
                <td><b>Vigueur</b></td>
                <td style="width:15%">{{ character.vig }}</td>
            </tr>
            <tr>
                <td><b>Vitalité</b></td>
                <td style="width:15%">{{ character.vit }}</td>
            </tr>
        </table>
    </div>
    <div id="character-stats-mental" class="col-md-2">
        <table class="table table-condensed table-striped table-bordered">
            <tr>
                <td><b>Intelligence</b></td>
                <td style="width:15%">{{ character.int }}</td>
            </tr>
            <tr>
                <td><b>Perception</b></td>
                <td style="width:15%">{{ character.per }}</td>
            </tr>
            <tr>
                <td><b>Charisme</b></td>
                <td style="width:15%">{{ character.cha }}</td>
            </tr>
            <tr>
                <td><b>Volonté</b></td>
                <td style="width:15%">{{ character.wil }}</td>
            </tr>
            <tr>
                <td><b>Mémoire</b></td>
                <td style="width:15%">{{ character.mem }}</td>
            </tr>
        </table>
    </div>
</div>
{% endblock %}